version: '3.8'

services:
  kong:
    image: kong:latest
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PLUGINS: bundled,acme,cors
      KONG_LUA_SSL_TRUSTED_CERTIFICATE: /etc/ssl/certs/ca-certificates.crt
    ports:
      - "8000:8000"  # Puerto para el tráfico de APIs
      - "8443:8443"  # Puerto para el tráfico HTTPS
      - "8001:8001"  # Puerto para el Admin API
      - "8444:8444"  # Puerto para el UI
    volumes:
      - ./kong.yml:/etc/kong/kong.yml
    networks:
      - kong-net
      - ndp

  konga:
    image: pantsel/konga:latest
    container_name: konga
    environment:
      DB_ADAPTER: "local"
    ports:
      - "1337:1337"
    networks:
      - kong-net
      - ndp
    depends_on:
      kong:
        condition: service_healthy

networks:
  kong-net:
    driver: bridge
  ndp:
    external: true